workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Detect Flutter project folder
        script: |
          # Find folder that contains pubspec.yaml
          PROJECT_DIR=$(find . -type f -name "pubspec.yaml" ! -path "*/build/*" -exec dirname {} \; | head -n 1)
          echo "Detected Flutter project in: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          flutter pub get
      - name: Build release APK
        script: |
          cd "$PROJECT_DIR"
          flutter build apk --release
    artifacts:
      - '**/build/app/outputs/flutter-apk/app-release.apk'
    publishing:
      install_dependencies: false
