workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Find Flutter project and install dependencies
        script: |
          cd "$(find . -name pubspec.yaml -exec dirname {} \; | head -n 1)"
          flutter pub get
      - name: Build release APK
        script: |
          cd "$(find . -name pubspec.yaml -exec dirname {} \; | head -n 1)"
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/app-release.apk"
