workflows:
  flutter-workflow:
    name: Flutter Workflow
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          cd FitQuest
          flutter pub get
      - name: Build APK
        script: |
          cd FitQuest
          flutter build apk --release
    artifacts:
      - FitQuest/build/app/outputs/flutter-apk/app-release.apk
